services:
  backend:
    build: ./backend
    container_name: lifecoach_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: lifecoach_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:15
    container_name: lifecoach_db
    restart: always
    environment:
      POSTGRES_USER: lifecoach_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: lifecoach_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
