services:
  db:
    image: postgres:15
    container_name: lifecoach_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d lifecoach_db -U lifecoach_user"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    networks:
      - lifenetwork
    environment:
      POSTGRES_USER: lifecoach_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: lifecoach_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6003:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lifecoach_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lifenetwork
    ports:
      - "6002:8000"
    volumes:
      - ./backend:/workspace/backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lifecoach_frontend
    restart: always
    depends_on:
      - backend
    networks:
      - lifenetwork
    ports:
      - "6001:80"
    volumes:
      - ./frontend:/workspace/frontend
      - ./frontend/node_modules:/workspace/frontend/node_modules

volumes:
  postgres_data:

networks:
  lifenetwork:
